name: findcribs
description: A new Flutter project.

version: 1.0.14+15

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  # <<<<<<< gabriel
  get: ^4.6.1
  # =======
  animated_splash_screen: ^1.1.0
  introduction_screen: ^3.1.14
  smooth_page_indicator: ^1.0.0+2
  dotted_border: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  flutter_form_builder: 
  http:
  fluttertoast: ^8.2.8
  cached_network_image: ^3.2.0
  progress_indicators: ^1.0.0
  google_sign_in: ^6.2.1
  form_builder_validators: 
  multi_select_flutter: ^4.1.2
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  just_the_tooltip: ^0.0.12
  socket_io_client: ^2.0.0
  custom_pop_up_menu: ^1.2.4
  image_cropper: ^8.0.2
  url_launcher: ^6.1.5
  visibility_detector: ^0.4.0+2
  timeago: ^3.3.0
  flutter_keyboard_visibility: ^6.0.0
  firebase_core: ^3.3.0
  # firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^15.0.4
  image_picker: ^1.1.2
  flutter_switch: ^0.3.2
  # camera: ^0.10.0+4
  awesome_dialog: ^3.0.2
  webview_flutter: ^4.8.0
  photo_view: ^0.15.0
  connectivity_plus: 
  flutter_local_notifications: ^17.2.2
  syncfusion_flutter_sliders: ^30.1.37
  permission_handler: ^11.3.1
  file_picker: ^8.0.7
  badges: ^3.1.2
  external_path: ^1.0.3
  upgrader: ^10.3.0
  loading_more_list: ^7.1.0
  share_plus: ^10.0.0
  flutter_intro: ^3.0.2
  infinite_scroll_pagination: ^4.0.0
  nb_utils: ^7.0.4
  path: any
  firebase_in_app_messaging: ^0.8.0+4

  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^11.2.1
  flutter_image_compress: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # disable-swift-package-manager: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
    - assets/
    - lib/assets/icons/
    - assets/json/nigeria-state-and-lgas.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: lib/assets/fonts/RedHatDisplay-Bold.ttf
    - family: RedHatDisplayLight
      fonts:
        - asset: lib/assets/fonts/RedHatDisplay-Light.ttf
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages