// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBV8pRah3vw94P7WeLAZN0wWJbEZb66A',
    appId: '1:285049044019:android:88c83f29f09c36a5e7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    storageBucket: 'findcribs-917f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55miJFVJYMxnbedTQLfvXooB2oZQTEXw',
    appId: '1:285049044019:ios:29556618611cd755e7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    storageBucket: 'findcribs-917f9.firebasestorage.app',
    androidClientId: '285049044019-2pufghms7pv3682duirssfqt63iarsr0.apps.googleusercontent.com',
    iosClientId: '285049044019-88f30jj3srd4ci6mvkhhrd47j6pl1u81.apps.googleusercontent.com',
    iosBundleId: 'com.findcribs.ng',
  );
}
