// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiG8xOsw7w9NURZuKZTPS6FPjXf81Y_qw',
    appId: '1:285049044019:web:24fca3df205ef3aae7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    authDomain: 'findcribs-917f9.firebaseapp.com',
    storageBucket: 'findcribs-917f9.appspot.com',
    measurementId: 'G-8JQX830EG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBV8pRah3vw94P7WeLAZN0wWJbEZb66A',
    appId: '1:285049044019:android:99a56f6483699337e7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    storageBucket: 'findcribs-917f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55miJFVJYMxnbedTQLfvXooB2oZQTEXw',
    appId: '1:285049044019:ios:5c9b2b3745b6b9d7e7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    storageBucket: 'findcribs-917f9.appspot.com',
    androidClientId: '285049044019-2pufghms7pv3682duirssfqt63iarsr0.apps.googleusercontent.com',
    iosClientId: '285049044019-ogi4una7gkgh4qbapag1o488bphulhep.apps.googleusercontent.com',
    iosBundleId: 'com.findcribs.findcribs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55miJFVJYMxnbedTQLfvXooB2oZQTEXw',
    appId: '1:285049044019:ios:5c9b2b3745b6b9d7e7f746',
    messagingSenderId: '285049044019',
    projectId: 'findcribs-917f9',
    storageBucket: 'findcribs-917f9.appspot.com',
    androidClientId: '285049044019-2pufghms7pv3682duirssfqt63iarsr0.apps.googleusercontent.com',
    iosClientId: '285049044019-ogi4una7gkgh4qbapag1o488bphulhep.apps.googleusercontent.com',
    iosBundleId: 'com.findcribs.findcribs',
  );
}
